[versions]
agp = "8.11.1"
browser = "1.9.0"
dagger = "2.57.2"
glide = "5.0.5"
kotlin = "2.0.21"
lifecycleViewmodelKtx = "2.10.0"
material = "1.12.0"
junit = "4.13.2"
recyclerview = "1.4.0"
recyclerviewSelection = "1.2.0"
retrofit = "3.0.0"

[libraries]
browser = { module = "androidx.browser:browser", version.ref = "browser" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleViewmodelKtx" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
material = { module = "com.google.android.material:material", version.ref = "material" }
junit = { module = "junit:junit", version.ref = "junit" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
recyclerview-selection = { module = "androidx.recyclerview:recyclerview-selection", version.ref = "recyclerviewSelection" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
